export const POKER_FACTORY_ABI = [
  {
    type: "function",
    name: "createTable",
    inputs: [
      { name: "buyIn", type: "uint256" },
      { name: "smallBlind", type: "uint256" },
      { name: "bigBlind", type: "uint256" },
      { name: "maxPlayers", type: "uint256" },
      { name: "tableName", type: "string" },
    ],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getAllTables",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTableInfo",
    inputs: [{ name: "table", type: "address" }],
    outputs: [
      { name: "buyInAmount", type: "uint256" },
      { name: "smallBlindAmount", type: "uint256" },
      { name: "bigBlindAmount", type: "uint256" },
      { name: "playerCount", type: "uint256" },
      { name: "potAmount", type: "uint256" },
      { name: "phaseValue", type: "uint8" },
      { name: "name", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTable",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTableCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTablesByBuyIn",
    inputs: [{ name: "targetBuyIn", type: "uint256" }],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CHIP_TOKEN",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CTX_CALLBACK_VALUE_WEI",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "TableCreated",
    inputs: [
      { name: "table", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "tableName", type: "string", indexed: false },
      { name: "buyIn", type: "uint256", indexed: false },
      { name: "smallBlind", type: "uint256", indexed: false },
      { name: "bigBlind", type: "uint256", indexed: false },
      { name: "maxPlayers", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
