export const POKER_GAME_ABI = [
  {
    type: "function",
    name: "sitDown",
    inputs: [{ name: "viewerKey", type: "tuple", components: [{ name: "x", type: "bytes32" }, { name: "y", type: "bytes32" }] }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fold",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "check",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "call",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "raise",
    inputs: [{ name: "raiseAmount", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "readyUp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unready",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestLeave",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelLeave",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "leaveTable",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forfeitAndLeave",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "phase",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pot",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayer",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCommunityCards",
    inputs: [],
    outputs: [{ name: "", type: "uint8[5]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activePlayerCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEncryptedCards",
    inputs: [{ name: "playerIndex", type: "uint256" }],
    outputs: [{ name: "", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMyEncryptedCards",
    inputs: [],
    outputs: [{ name: "", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMyHoleCards",
    inputs: [],
    outputs: [{ name: "card1", type: "uint8" }, { name: "card2", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "areMyCardsRevealed",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isCardsRevealed",
    inputs: [{ name: "playerIndex", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPhaseName",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "evaluatePlayerHand",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "handRank", type: "uint8" }, { name: "primary", type: "uint8" }, { name: "secondary", type: "uint8" }, { name: "tertiary", type: "uint8" }, { name: "quaternary", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentBet",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dealer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "handNumber",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isReady",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "readyCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerInfo",
    inputs: [{ name: "idx", type: "uint256" }],
    outputs: [{ name: "addr", type: "address" }, { name: "active", type: "bool" }, { name: "acted", type: "bool" }, { name: "bet", type: "uint256" }, { name: "allIn", type: "bool" }, { name: "stackBal", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerStack",
    inputs: [{ name: "idx", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentTurnIndex",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BUY_IN",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SMALL_BLIND",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BIG_BLIND",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_PLAYERS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CTX_CALLBACK_VALUE_WEI",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tableName",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isLeaveRequested",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minimumCtxReserve",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_BET",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlayerJoined",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "seat", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameStarted",
    inputs: [{ name: "handNumber", type: "uint256", indexed: false }, { name: "dealer", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerFolded",
    inputs: [{ name: "player", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerChecked",
    inputs: [{ name: "player", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerCalled",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerRaised",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "totalBet", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "FlopDealt",
    inputs: [{ name: "card1", type: "uint8", indexed: false }, { name: "card2", type: "uint8", indexed: false }, { name: "card3", type: "uint8", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "TurnDealt",
    inputs: [{ name: "card", type: "uint8", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RiverDealt",
    inputs: [{ name: "card", type: "uint8", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShowdownInitiated",
    inputs: [{ name: "activePlayerCount", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "CardsRevealed",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "card1", type: "uint8", indexed: false }, { name: "card2", type: "uint8", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PotAwarded",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "HandComplete",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "PhaseChanged",
    inputs: [{ name: "newPhase", type: "uint8", indexed: false }, { name: "handNumber", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerReady",
    inputs: [{ name: "player", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerUnready",
    inputs: [{ name: "player", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "TurnChanged",
    inputs: [{ name: "playerIndex", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerAction",
    inputs: [{ name: "player", type: "address", indexed: true }, { name: "action", type: "string", indexed: false }, { name: "amount", type: "uint256", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "HandResult",
    inputs: [{ name: "winners", type: "address[]", indexed: false }, { name: "amounts", type: "uint256[]", indexed: false }, { name: "handNames", type: "string[]", indexed: false }],
    anonymous: false,
  },
] as const;
